### PR TITLE
(#23) roman numerals task

### PR DESCRIPTION
**Pull request by zlenyk**

### CODE REVIEW

**Comment by neojski** [comment]
Looks well. Just don't use `deepEqual` as it's not necessary here. Use `strictEqual`. For reference see: http://api.qunitjs.com/category/assert/.

I also feel like roman numerals are so complicated that 6 random numbers are not enough if we wanna return all numbers between 1 and 4000. Try to add some tests to have at least 20 of them.

**Comment by zlenyk** [comment]
hej, móh³by¶ jeszcze raz pulln±æ mojego taska i go zmergowaæ? :)

2013/5/22 Tomasz Ko³odziejski notifications@github.com

**Comment by neojski** [comment]
Looks like you didn't switch to `strictEqual` (or you missed that change)

**Comment by neojski** [comment]
Also, you added tmp file ( tasks/homework/roman-numerals.js~ )

**Comment by zlenyk** [comment]
should be all right now :P

**Comment by neojski** [comment]
Fixed commit message and merged in 40ad8ccf3215258c193bb1654bd146ec245b529e.

Cheers!

**Pull request closed without merging**
